### ISSUE TITLE
Subtask #10: Add purchase mode

### ISSUE THREAD

**Issue by zebraf1** [zebraf1/Kassa#16]
Subtask of #10

Create purchase page:

  - [x] new main layout without other menus
  - [ ] add 3 buttons to main page: Cash, Credit, Credit refund
    - [ ] Credit refund - ask amount deposited, member search, password
    - [x] Credit - select products, amounts (js basket, support barcode reader), member search, password
    - [x] Cash - select products (same as credit)
  - [x] Buttons to Complete or Cancel payment
  - [x] new PurchaseController and new Payment action for all 3 types
  - [x] Point of Sale
    - New page for admins to display points of sale and mark current browser one (database entry with hash)
    - PoS browser sets a persistent cookie with hash. When user is logged out, the welcome page forwards to purchase page.
    - Special authentication role, limited access

**Comment by zebraf1** [comment]
Ülejäänud asjad eraldi kannetesse
